### PR TITLE
Update to fix reboot bug

### PR DESCRIPTION
**Pull request by dgirard96789**
Added line to prevent watchdog timeout in event of an API connection error (seems to happen automatically after about 15 mins for some reason)

### CODE REVIEW

**Comment by cbpowell** [comment]
I incorporated your BN-Link config into mine, and it's now listed in the `configs` folder. I'm trying to keep the configs simple and un-opinionated at this point, so I did remove some stuff from your config - but if I missed something you've found important please correct me!

I'll close this PR for now since things have diverged.

**Comment by dgirard96789** [comment]
OK, thanks.  All I wanted to really do was contribute the GPIO settings.

Looks like my problems have been related to the API.  Apparently if the API
is enabled, but HA isn't using it, the device will reboot periodically.
My mistake.

I'm now using your original code with the GPIO's set for these BN-Links.

Thanks again for everything!

Also, FYI...I noticed with the :latest source code in ESPHome (docker) that
the devices reset the relay (power off then back on) when the code reboots,
but with the :Beta stream, the device resets without resetting the relay!

**Comment by cbpowell** [comment]
Yeah now that you mention the resets with the API that rings a bell, ha.

Glad you find it useful! And thanks for the heads up on resets on the beta.

**Comment by drd0c** [comment]
@cbpowell, don't want to open an issue if this is just me, but I saw you had been running EFUN SH331s. I have a handful of them running ESPSense and love the visibility, but they all stop logging for about an hour (show 0w) from 4-5 AM, and they will occasionally power-cycle spontaneously. This has happened since I deployed them several weeks ago. Do you have any input on something I might be missing? Maybe I don't need the api: line if I'm not doing automations within ESPHome?
Any response is appreciated. Sorry if this is the wrong mechanism to ask.

**Comment by cbpowell** [comment]
@drd0c No worries, this is the place to ask!

As it's been a few weeks/months (is it *still* 2020?!) since I was really deep into this, the ESPHome ins and outs aren't quite as fresh in my head, but yep if you aren't using the HomeAssistant API integration I'd recommend commenting out the `api:` line.

ESPHome devices will reboot if they can't connect to the API when told to expect one, although the default timeout is 15 minutes (per [here](https://esphome.io/components/api.html#configuration-variables)) so I'm not sure where the 4-5 AM reset comes from. The spontaneous power cycles are probably that API-related reboot though.

My only active SH331 has been plugged into something that's been mostly off anyway, so I can't double check for a 0w hour gap. I'll have to move it to something else and see - but I also have a HomeAssistant API running.

**Comment by drd0c** [comment]
@cbpowell well I don't know much about the api: stuff, but it seems that is needed if I'm going to use Home Assistant to query logs from the device, etc. So disabling it isn't an option. Maybe I will try to change reboot_timeout to 0 to disable (knowing this isn't a permanent fix) and see how that changes things.

Thanks for the response and let me know if you have other thoughts. 3 of my five units (all identical configuration except names and if the status LED is enabled or not) have the issue where they turn themselves of and on a couple of times at 4AM and don't report for an hour.

**Comment by cbpowell** [comment]
@drd0c you will need it if you plan to use your device with Home Assistant - sorry I might have misinterpreted your comment and assumed you weren't using Home Assistant. But to clarify, if you aren't using HA _now_, I'd say comment out the API line for now and then do a new build with it when you do get HA set up.

The 4AM resets are weird though, could that possibly be a Wifi connectivity issue of some kind? Like is your router/access point doing an automated upgrade or reboot at that time, or something else that would affect the plug's ability to connect? I have several ESPHome devices running (both with and without ESPSense) and haven't run into something like that as far as I know.

**Comment by drd0c** [comment]
I think it might be related to DHCP renewal/router/static vs dynamic
leases. Still gathering data. Thanks!

**Pull request closed without merging**
